addEventHandler ( "onClientResourceStart",  getResourceRootElement(getThisResource()), -- 272
	function ()
		local txd = engineLoadTXD ( "des_nwtownpolice.txd" )
		engineImportTXD ( txd, 11611 )
		local txd = engineLoadTXD ( "barracks.txd" )
		engineImportTXD ( txd, 433 )
		local dff = engineLoadDFF ( "barracks.dff", 433 )
		engineReplaceModel ( dff, 433 )
		local txd = engineLoadTXD ( "moonbeam.txd" )
		engineImportTXD ( txd, 418 )
		local dff = engineLoadDFF ( "moonbeam.dff", 418 )
		engineReplaceModel ( dff, 418 )
		
		local txd = engineLoadTXD ( "t-51b.txd" )
		engineImportTXD ( txd, 257 )
		local dff = engineLoadDFF ( "t-51b.dff", 257 )
		engineReplaceModel ( dff, 257 )
		
		local txd = engineLoadTXD ( "2.txd" )
		engineImportTXD ( txd, 233 )
		local dff = engineLoadDFF ( "2.dff", 233 )
		engineReplaceModel ( dff, 233 )
		
		local txd = engineLoadTXD ( "t-52c.txd" )
		engineImportTXD ( txd, 253 )
		local dff = engineLoadDFF ( "t-51b.dff", 253 )
		engineReplaceModel ( dff, 253 )
		
		local txd = engineLoadTXD ( "deathclaw.txd" )
		engineImportTXD ( txd, 237 )
		local dff = engineLoadDFF ( "deathclaw.dff", 237 )
		engineReplaceModel ( dff, 237 )
		
		
		-- скины
		local txd = engineLoadTXD ( "Ranger.txd" )
		engineImportTXD ( txd, 23 )
		local dff = engineLoadDFF ( "Ranger.dff", 23 ) -- рэйнджер
		engineReplaceModel ( dff, 23 )
		local txd = engineLoadTXD ( "EnclaveScientist.txd" )
		engineImportTXD ( txd, 20 )
		local dff = engineLoadDFF ( "EnclaveScientist.dff", 20 )
		engineReplaceModel ( dff, 20 ) 
		local txd = engineLoadTXD ( "Remnant.txd" )
		engineImportTXD ( txd, 21 )
		local dff = engineLoadDFF ( "Remnant.dff", 21 )
		engineReplaceModel ( dff, 21 ) 
		local txd = engineLoadTXD ( "troop.txd" )
		engineImportTXD ( txd, 22 )
		local dff = engineLoadDFF ( "troop.dff", 22 )
		engineReplaceModel ( dff, 22 ) 
		
		
		local txd = engineLoadTXD ( "bfinject.txd" )
		engineImportTXD ( txd, 424 )
		local dff = engineLoadDFF ( "bfinject.dff", 424 )
		engineReplaceModel ( dff, 424 )
		
		local txd = engineLoadTXD ( "bravura.txd" )
		engineImportTXD ( txd, 401 )
		local dff = engineLoadDFF ( "bravura.dff", 401 )
		engineReplaceModel ( dff, 401 )
		
		local txd = engineLoadTXD ( "blistac.txd" )
		engineImportTXD ( txd, 496 )
		local dff = engineLoadDFF ( "blistac.dff", 496 )
		engineReplaceModel ( dff, 496 )
		
		local txd = engineLoadTXD ( "sabre.txd" )
		engineImportTXD ( txd, 475 )
		local dff = engineLoadDFF ( "sabre.dff", 475 )
		engineReplaceModel ( dff, 475 )
		
			local txd = engineLoadTXD ( "bat.txd" )
		engineImportTXD ( txd, 336 )
		local dff = engineLoadDFF ( "bat.dff", 336 )
		engineReplaceModel ( dff, 336 )
		local txd = engineLoadTXD ( "chromegun.txd" )
		engineImportTXD ( txd, 349 )
		local dff = engineLoadDFF ( "chromegun.dff", 349 )
		engineReplaceModel ( dff, 349 )
		local txd = engineLoadTXD ( "sandking.txd" )
		engineImportTXD ( txd, 495 )
		local dff = engineLoadDFF ( "sandking.dff", 495 )
		engineReplaceModel ( dff, 495 )
		
		
		local txd = engineLoadTXD ( "flame.txd" )
		engineImportTXD ( txd, 361 )
		local dff = engineLoadDFF ( "flame.dff", 361 )
		engineReplaceModel ( dff, 361 )
		local txd = engineLoadTXD ( "minigun.txd" )
		engineImportTXD ( txd, 362 )
		local dff = engineLoadDFF ( "minigun.dff", 362 )
		engineReplaceModel ( dff, 362 )
		
		
		-- local txd = engineLoadTXD ( "SK_ARMOR.txd" )
		-- engineImportTXD ( txd, 244 )
		-- local dff = engineLoadDFF ( "SK_ARMOR.dff", 244 )
		-- engineReplaceModel ( dff, 244 )
		
		local col = engineLoadCOL( "fallout/kix.col" )
		engineReplaceCOL( col, 3594 )
		local txd = engineLoadTXD( "fallout/kix.txd" )
		engineImportTXD( txd, 3594 )
		local dff = engineLoadDFF ( "fallout/kix.dff", 3594 )
		engineReplaceModel ( dff, 3594 )


		local col = engineLoadCOL( "fallout/crate.col" )
		engineReplaceCOL( col, 1371 )
		local txd = engineLoadTXD( "fallout/crate.txd" )
		engineImportTXD( txd, 1371 )
		local dff = engineLoadDFF ( "fallout/crate.dff", 1371 )
		engineReplaceModel ( dff, 1371 )

		local col = engineLoadCOL( "fallout/car02.col" )
		engineReplaceCOL( col, 3593 )
		local txd = engineLoadTXD( "fallout/car02.txd" )
		engineImportTXD( txd, 3593 )
		local dff = engineLoadDFF ( "fallout/car02.dff", 3593 )
		engineReplaceModel ( dff, 3593 )

		local col = engineLoadCOL( "fallout/truck01.col" )
		engineReplaceCOL( col, 2809 )
		local txd = engineLoadTXD( "fallout/truck01.txd" )
		engineImportTXD( txd, 2809 )
		local dff = engineLoadDFF ( "fallout/truck01.dff", 2809 )
		engineReplaceModel ( dff, 2809 )

		local col = engineLoadCOL( "fallout/police.col" )
		engineReplaceCOL( col, 2810 )
		local txd = engineLoadTXD( "fallout/police.txd" )
		engineImportTXD( txd, 2810 )
		local dff = engineLoadDFF ( "fallout/police.dff", 2810 )
		engineReplaceModel ( dff, 2810 )

		local col = engineLoadCOL( "fallout/ranch.col" )
		engineReplaceCOL( col, 3648 )
		local txd = engineLoadTXD( "fallout/ranch.txd" )
		engineImportTXD( txd, 3648 )
		local dff = engineLoadDFF ( "fallout/ranch.dff", 3648 )
		engineReplaceModel ( dff, 3648 )

		local col = engineLoadCOL( "fallout/ranch2.col" )
		engineReplaceCOL( col, 2812 )
		local txd = engineLoadTXD( "fallout/ranch.txd" )
		engineImportTXD( txd, 2812 )
		local dff = engineLoadDFF ( "fallout/ranch2.dff", 2812 )
		engineReplaceModel ( dff, 2812 )

		local col = engineLoadCOL( "fallout/ranch3.col" )
		engineReplaceCOL( col, 2813 )
		local txd = engineLoadTXD( "fallout/ranch3.txd" )
		engineImportTXD( txd, 2813 )
		local dff = engineLoadDFF ( "fallout/ranch3.dff", 2813 )
		engineReplaceModel ( dff, 2813 )

		local col = engineLoadCOL( "fallout/dest8.col" )
		engineReplaceCOL( col, 2814 )
		local txd = engineLoadTXD( "fallout/dest8.txd" )
		engineImportTXD( txd, 2814 )
		local dff = engineLoadDFF ( "fallout/dest8.dff", 2814 )
		engineReplaceModel ( dff, 2814 )

		local col = engineLoadCOL( "fallout/home.col" )
		engineReplaceCOL( col, 2815 )
		local txd = engineLoadTXD( "fallout/home.txd" )
		engineImportTXD( txd, 2815 )
		local dff = engineLoadDFF ( "fallout/home.dff", 2814 )
		engineReplaceModel ( dff, 2815 )

		local col = engineLoadCOL( "fallout/radio.col" )
		engineReplaceCOL( col, 2816 )
		local txd = engineLoadTXD( "fallout/radio.txd" )
		engineImportTXD( txd, 2816 )
		local dff = engineLoadDFF ( "fallout/radio.dff", 2816)
		engineReplaceModel ( dff, 2816 )
		
		local col = engineLoadCOL( "fallout/house2.col" )
		engineReplaceCOL( col, 2817 )
		local txd = engineLoadTXD( "fallout/house2.txd" )
		engineImportTXD( txd, 2817 )
		local dff = engineLoadDFF ( "fallout/house2.dff", 2817 )
		engineReplaceModel ( dff, 2817 )

		local col = engineLoadCOL( "fallout/shack.col" )
		engineReplaceCOL( col, 2818 )
		local txd = engineLoadTXD( "fallout/shack.txd" )
		engineImportTXD( txd, 2818 )
		local dff = engineLoadDFF ( "fallout/shack.dff", 2818 )
		engineReplaceModel ( dff, 2818 )

		local col = engineLoadCOL( "fallout/oldwest.col" )
		engineReplaceCOL( col, 2819 )
		local txd = engineLoadTXD( "fallout/oldwest.txd" )
		engineImportTXD( txd, 2819 )
		local dff = engineLoadDFF ( "fallout/oldwest.dff", 2819 )
		engineReplaceModel ( dff, 2819 )

		local col = engineLoadCOL( "fallout/gs_house.col" )
		engineReplaceCOL( col, 2820 )
		local txd = engineLoadTXD( "fallout/gs_house.txd" )
		engineImportTXD( txd, 2820 )
		local dff = engineLoadDFF ( "fallout/gs_house.dff", 2820 )
		engineReplaceModel ( dff, 2820 )

		local col = engineLoadCOL( "fallout/gs_house02.col" )
		engineReplaceCOL( col, 2821 )
		local txd = engineLoadTXD( "fallout/gs_house02.txd" )
		engineImportTXD( txd, 2821 )
		local dff = engineLoadDFF ( "fallout/gs_house02.dff", 2821 )
		engineReplaceModel ( dff, 2821 )
		
		local col = engineLoadCOL( "fallout/fungus.col" )
		engineReplaceCOL( col, 2823 )
		local txd = engineLoadTXD( "fallout/fungus.txd" )
		engineImportTXD( txd, 2823 )
		local dff = engineLoadDFF ( "fallout/fungus.dff", 2823 )
		engineReplaceModel ( dff, 2823 )
		
		
		local col = engineLoadCOL( "fallout/reload.col" )
		engineReplaceCOL( col, 1770 )
		local txd = engineLoadTXD( "fallout/reload.txd" )
		engineImportTXD( txd, 1770 )
		local dff = engineLoadDFF ( "fallout/reload.dff", 1770 )
		engineReplaceModel ( dff, 1770 )
		
	end)