addEventHandler("onClientResourceStart", resourceRoot,
    function()
        myShader,tecName = dxCreateShader( "clientshader.fx" )
        grassShader,tecName = dxCreateShader( "clientshader.fx" )
        grassShader_r,tecName = dxCreateShader( "clientshader.fx" )
        grassShader_r2,tecName = dxCreateShader( "clientshader.fx" )
        grassRoadShader,tecName = dxCreateShader( "clientshader.fx" )
        grassRoadShader_r,tecName = dxCreateShader( "clientshader.fx" )
        rockShader,tecName = dxCreateShader( "clientshader.fx" )
        roadShader,tecName = dxCreateShader( "clientshader.fx" )
        roadShader_r,tecName = dxCreateShader( "clientshader.fx" )
        --cocnreteShader,tecName = dxCreateShader( "clientshader.fx" )
        cocnreteShader_r,tecName = dxCreateShader( "clientshader.fx" )
        cocnreteShader,tecName = dxCreateShader( "clientshader.fx" )
        stoneShader,tecName = dxCreateShader( "clientshader.fx" )
        gravelShader,tecName = dxCreateShader( "clientshader.fx" )
        gravelRoadShader,tecName = dxCreateShader( "clientshader.fx" )
        trainGravelShader,tecName = dxCreateShader( "clientshader.fx" )
        trainShader,tecName = dxCreateShader( "clientshader.fx" )
        newConcreteShader,tecName = dxCreateShader( "clientshader.fx" )
        grassBurnShader,tecName = dxCreateShader( "clientshader.fx" )
        grassMiddleBurnShader,tecName = dxCreateShader( "clientshader.fx" )
        countryRoadShader,tecName = dxCreateShader( "clientshader.fx" )
        myImage = dxCreateTexture( "1.dds" )
        grassRock = dxCreateTexture( "grassRock.dds" )
        grassRock_r = dxCreateTexture( "grassRock_r.dds" )
        grassRock_r2 = dxCreateTexture( "grassRock_r2.dds" )
        grassRoad = dxCreateTexture( "21.dds" )
        grassRoad_r = dxCreateTexture( "21_r.dds" )
        rock = dxCreateTexture( "24.png" )
        road = dxCreateTexture( "13.dds" )
        road_r = dxCreateTexture( "13.dds" )
        cocnrete = dxCreateTexture( "38.dds" )
        cocnrete_r = dxCreateTexture( "38_r.dds" )
        stone = dxCreateTexture( "24.dds" )
        gravel = dxCreateTexture( "20.png" )
        gravelRoad = dxCreateTexture( "52.png" )
        train = dxCreateTexture( "14.png" )
        trainGravel = dxCreateTexture( "15.png" )
        newConcrete = dxCreateTexture( "58.png" )
        grassBurn = dxCreateTexture( "70.png" )
        grassMiddleBurn = dxCreateTexture( "27.dds" )
        countryRoad = dxCreateTexture( "32.dds" )
        if myShader and myImage then
            dxSetShaderValue( myShader, "tex0", myImage )
            dxSetShaderValue( grassShader, "tex0", grassRock )
            dxSetShaderValue( grassShader_r, "tex0", grassRock_r )
            dxSetShaderValue( grassShader_r2, "tex0", grassRock_r2 )
            dxSetShaderValue( grassRoadShader, "tex0", grassRoad )
            dxSetShaderValue( grassRoadShader_r, "tex0", grassRoad_r )
            dxSetShaderValue( rockShader, "tex0", rock )
            dxSetShaderValue( roadShader, "tex0", road )
            dxSetShaderValue( roadShader_r, "tex0", road_r )
            dxSetShaderValue( cocnreteShader_r, "tex0", cocnrete_r )
            dxSetShaderValue( cocnreteShader, "tex0", cocnrete )
            dxSetShaderValue( stoneShader, "tex0", stone )
            dxSetShaderValue( gravelShader, "tex0", gravel )
            dxSetShaderValue( gravelRoadShader, "tex0", gravelRoad )
            dxSetShaderValue( trainShader, "tex0", train )
            dxSetShaderValue( trainGravelShader, "tex0", trainGravel )
            dxSetShaderValue( newConcreteShader, "tex0", newConcrete )
            dxSetShaderValue( grassBurnShader, "tex0", grassBurn )
            dxSetShaderValue( grassMiddleBurnShader, "tex0", grassMiddleBurn )
            dxSetShaderValue( countryRoadShader, "tex0", countryRoad )
            --dxSetShaderValue( grassShader, "tex0", grass )
		--	engineApplyShaderToWorldTexture( myShader, "dt_road*" )
			engineApplyShaderToWorldTexture( stoneShader, "sw_stones" )
			engineApplyShaderToWorldTexture( myShader, "des_dustconc" )
			engineApplyShaderToWorldTexture( myShader, "desertgryard256" )
			engineApplyShaderToWorldTexture( myShader, "desgreengrassmix" )
			engineApplyShaderToWorldTexture( myShader, "desgrassbrn*" )
			engineApplyShaderToWorldTexture( myShader, "yardgrass*" )
			engineApplyShaderToWorldTexture( myShader, "sl_sfngrass01" )
			engineApplyShaderToWorldTexture( myShader, "forestfloor*" )
			engineApplyShaderToWorldTexture( myShader, "sw_grass*" )
			engineApplyShaderToWorldTexture( myShader, "grass*" )
			engineApplyShaderToWorldTexture( myShader, "des_dirt*" )
			engineApplyShaderToWorldTexture( myShader, "des_grass2scrub*" )
			engineApplyShaderToWorldTexture( myShader, "sw_sand" )
			engineApplyShaderToWorldTexture( myShader, "bow_church_dirt" )
			engineApplyShaderToWorldTexture( rockShader, "vgs_rockmid*" )
			engineApplyShaderToWorldTexture( rockShader, "des_rocky*" )
			engineApplyShaderToWorldTexture( rockShader, "rock_country128" )
			engineApplyShaderToWorldTexture( rockShader, "rocktq128*" )
			engineApplyShaderToWorldTexture( roadShader_r, "tar_1line256hv" )
			engineApplyShaderToWorldTexture( roadShader, "cos_hiway*" )
			engineApplyShaderToWorldTexture( rockShader, "cw2_mount*" )
			engineApplyShaderToWorldTexture( roadShader_r, "tar_1linefree*" )
			engineApplyShaderToWorldTexture( roadShader_r, "tar_lineslipway*" )
			engineApplyShaderToWorldTexture( roadShader, "roadnew*" )
			engineApplyShaderToWorldTexture( roadShader, "vegasroad*" )
			engineApplyShaderToWorldTexture( roadShader, "dt_road" )
			engineApplyShaderToWorldTexture( roadShader, "dt_road_stoplinea" )
			engineApplyShaderToWorldTexture( roadShader_r, "sf_junction5" )
			engineApplyShaderToWorldTexture( roadShader, "hiwaymidlle_256" )
			engineApplyShaderToWorldTexture( roadShader, "sf_road*" )
			engineApplyShaderToWorldTexture( roadShader, "ws_freeway3" )
			engineApplyShaderToWorldTexture( cocnreteShader_r, "ws_freeway2" )
			engineApplyShaderToWorldTexture( cocnreteShader, "sf_pave*" )
			engineApplyShaderToWorldTexture( cocnreteShader, "pavebsand256" )
			engineApplyShaderToWorldTexture( cocnreteShader, "ws_tunnelwall*" )
			engineApplyShaderToWorldTexture( cocnreteShader, "kbpavement*" )
			engineApplyShaderToWorldTexture( cocnreteShader, "craproad6_lae" )
			engineApplyShaderToWorldTexture( roadShader, "craproad7_lae7" )
			engineApplyShaderToWorldTexture( roadShader, "craproad2_lae" )
			engineApplyShaderToWorldTexture( roadShader, "craproad1_lae" )
			engineApplyShaderToWorldTexture( roadShader_r, "crossing_law*" )
			engineApplyShaderToWorldTexture( cocnreteShader_r, "stormdrain3*" )
			engineApplyShaderToWorldTexture( cocnreteShader, "stormdrain5*" )
			engineApplyShaderToWorldTexture( cocnreteShader, "block2" )
			engineApplyShaderToWorldTexture( cocnreteShader_r, "newpavement" )
			engineApplyShaderToWorldTexture( cocnreteShader_r, "coasty_bit3_sfe" )
			engineApplyShaderToWorldTexture( myShader, "dirtblendlit" )
			engineApplyShaderToWorldTexture( grassShader, "desertgravelgrass256" )
			engineApplyShaderToWorldTexture( grassRoadShader_r, "desertgravelgrassroad" )
			engineApplyShaderToWorldTexture( grassShader, "sw_stonesgrass" )
			engineApplyShaderToWorldTexture( rockShader, "sw_rockgrass*" )
			engineApplyShaderToWorldTexture( rockShader, "dirtkb_64hv" )
			engineApplyShaderToWorldTexture( rockShader, "newgrnd1brn_128" )
			engineApplyShaderToWorldTexture( cocnreteShader_r, "trail_wall1" )
			engineApplyShaderToWorldTexture( cocnreteShader_r, "drvin_ground*" )
			engineApplyShaderToWorldTexture( cocnreteShader_r, "blendpavement*" )
			engineApplyShaderToWorldTexture( cocnreteShader_r, "vegaspavement*" )
			engineApplyShaderToWorldTexture( cocnreteShader_r, "concreteblock*" )
			engineApplyShaderToWorldTexture( cocnreteShader_r, "vegasdirtypave*" )
			engineApplyShaderToWorldTexture( cocnreteShader_r, "vgs_shopwall01_*" )
			engineApplyShaderToWorldTexture( cocnreteShader_r, "dirtywall_256*" )
			engineApplyShaderToWorldTexture( cocnreteShader_r, "sjmhoodlawn*" )
			engineApplyShaderToWorldTexture( stoneShader, "hiwayoutside_256" )
			engineApplyShaderToWorldTexture( stoneShader, "des_redrock*" )
			engineApplyShaderToWorldTexture( stoneShader, "des_yelrock*" )
			engineApplyShaderToWorldTexture( trainShader, "ws_traintrax*" )
			engineApplyShaderToWorldTexture( trainGravelShader, "ws_traingravel" )
			engineApplyShaderToWorldTexture( grassRoadShader, "sidewgrass1" )
			engineApplyShaderToWorldTexture( rockShader, "conc_slabgrey_256128" )
			--engineApplyShaderToWorldTexture( roadShader, "tar_freew*" )
			engineApplyShaderToWorldTexture( roadShader_r, "tar_1line256hvblenddrt" )
			engineApplyShaderToWorldTexture( roadShader_r, "tar_freew*" )
			engineApplyShaderToWorldTexture( roadShader, "snpedtest1" )
			engineApplyShaderToWorldTexture( grassShader_r, "sfn_rocktbrn128" )
			engineApplyShaderToWorldTexture( grassShader, "sfncn_rockgrass3" )
			engineApplyShaderToWorldTexture( grassShader_r, "rocktbrn128blnd" )
			engineApplyShaderToWorldTexture( grassShader, "rocktq128_grass4blend" )
			engineApplyShaderToWorldTexture( grassShader_r2, "vgs_rockbot*" )
			engineApplyShaderToWorldTexture( grassShader_r, "rock_country128blnd" )
			engineApplyShaderToWorldTexture( grassShader_r2, "blendrock2grgrass" )
			engineApplyShaderToWorldTexture( myShader, "desgreengrass" )
			engineApplyShaderToWorldTexture( myShader, "hiwaygravel*" )
			engineApplyShaderToWorldTexture( myShader, "hiway2sand*" )
			engineApplyShaderToWorldTexture( myShader, "des_scrub*" )
			engineApplyShaderToWorldTexture( myShader, "bow_church_grass_gen" )
			engineApplyShaderToWorldTexture( grassMiddleBurnShader, "sfn_rockhole" )
			engineApplyShaderToWorldTexture( grassRoadShader, "dt_road2grasstype4" )
			engineApplyShaderToWorldTexture( grassRoadShader, "hiwayinsideblend*" )
			--engineApplyShaderToWorldTexture( grassRoadShader, "hiwayinside5*" )
			--engineApplyShaderToWorldTexture( grassRoadShader, "hiwayinside*" )
			engineApplyShaderToWorldTexture( grassRoadShader, "hiwayinside*" )
			engineApplyShaderToWorldTexture( grassRoadShader, "cuntroad01_law" )
			engineApplyShaderToWorldTexture( grassRoadShader_r, "brngrss2stones" )
			engineApplyShaderToWorldTexture( grassRoadShader_r, "des_roadedge*" )
			engineApplyShaderToWorldTexture( myShader, "des_grass2dirt*" )
			engineApplyShaderToWorldTexture( myShader, "des_grass2dirt*" )
			engineApplyShaderToWorldTexture( myShader, "desstones_dirt*" )
			engineApplyShaderToWorldTexture( roadShader_r, "des_1line256" )
			engineApplyShaderToWorldTexture( roadShader_r, "des_1lineend" )
			--engineApplyShaderToWorldTexture( grassShader, "txgrass0_1" )
			engineApplyShaderToWorldTexture( gravelShader, "bow_grass_gryard" )
			engineApplyShaderToWorldTexture( gravelShader, "desertstones256" )
			engineApplyShaderToWorldTexture( countryRoadShader, "desmudtrail" )
			engineApplyShaderToWorldTexture( countryRoadShader, "dirttrack*" )
		--	engineApplyShaderToWorldTexture( myShader, "bullethitsmoke*" )
	--		engineApplyShaderToWorldTexture( myShader, "monsterb92wheel64", myImage )
        --    outputChatBox( "Shader using techinque " .. tecName ) --txgrass0_1
        else
        --    outputChatBox( "Problem - use: debugscript 3" )
        end
    end
)

