addEventHandler("onClientResourceStart", resourceRoot,
    function()
        myShader,tecName = dxCreateShader( "clientshader.fx" )
        grassShader,tecName = dxCreateShader( "clientshader.fx" )
        grassShader_r,tecName = dxCreateShader( "clientshader.fx" )
        grassShader_r2,tecName = dxCreateShader( "clientshader.fx" )
        grassRoadShader,tecName = dxCreateShader( "clientshader.fx" )
        grassRoadShader_r,tecName = dxCreateShader( "clientshader.fx" )
        rockShader,tecName = dxCreateShader( "clientshader.fx" )
        roadShader,tecName = dxCreateShader( "clientshader.fx" )
        roadShader_r,tecName = dxCreateShader( "clientshader.fx" )
        roadShader_r2,tecName = dxCreateShader( "clientshader.fx" )
        --cocnreteShader,tecName = dxCreateShader( "clientshader.fx" )
        cocnreteShader_r,tecName = dxCreateShader( "clientshader.fx" )
        cocnreteShader,tecName = dxCreateShader( "clientshader.fx" )
        stoneShader,tecName = dxCreateShader( "clientshader.fx" )
        gravelShader,tecName = dxCreateShader( "clientshader.fx" )
        gravelRoadShader,tecName = dxCreateShader( "clientshader.fx" )
        trainGravelShader,tecName = dxCreateShader( "clientshader.fx" )
        trainShader,tecName = dxCreateShader( "clientshader.fx" )
        newConcreteShader,tecName = dxCreateShader( "clientshader.fx" )
        grassBurnShader,tecName = dxCreateShader( "clientshader.fx" )
        grassMiddleBurnShader,tecName = dxCreateShader( "clientshader.fx" )
        countryRoadShader,tecName = dxCreateShader( "clientshader.fx" )
        sandGrassShader,tecName = dxCreateShader( "clientshader.fx" )
        rockGreenShader,tecName = dxCreateShader( "clientshader.fx" )
        blockShader,tecName = dxCreateShader( "clientshader.fx" )
        concGrassShader,tecName = dxCreateShader( "clientshader.fx" )
        parkingShader,tecName = dxCreateShader( "clientshader.fx" )
        waterShader,tecName = dxCreateShader( "clientshader.fx" )
        brickShader,tecName = dxCreateShader( "clientshader.fx" )
        grassNewShader,tecName = dxCreateShader( "clientshader.fx" )
        grassNewShader2,tecName = dxCreateShader( "clientshader.fx" )
        countryRoadShader_r,tecName = dxCreateShader( "clientshader.fx" )
        leavesShader,tecName = dxCreateShader( "clientshader.fx" )
        leavesShader2,tecName = dxCreateShader( "clientshader.fx" )
        stalkShader,tecName = dxCreateShader( "clientshader.fx" )
        roadShader_rr,tecName = dxCreateShader( "clientshader.fx" )
        fieldShader,tecName = dxCreateShader( "clientshader.fx" )
        cloudShader,tecName = dxCreateShader( "clientshader.fx" )
		--outputChatBox ( tostring ( cocnreteShader ) )
        myImage = dxCreateTexture( "1.png" )
        grassRock = dxCreateTexture( "30.png" )
        grassRock_r = dxCreateTexture( "30_r.png" )
        grassRock_r2 = dxCreateTexture( "30_r2.png" )
        grassRoad = dxCreateTexture( "21.png" )
        grassRoad_r = dxCreateTexture( "21_r.png" )
        rock = dxCreateTexture( "29.png" )
        road = dxCreateTexture( "13.png" )
        road_r = dxCreateTexture( "5.png" )
        cocnrete = dxCreateTexture( "38.png" )
        cocnrete_r = dxCreateTexture( "38_r.png" )
        stone = dxCreateTexture( "7.png" )
        gravel = dxCreateTexture( "20.png" )
        gravelRoad = dxCreateTexture( "52.png" )
        train = dxCreateTexture( "14.png" )
        trainGravel = dxCreateTexture( "15.png" )
        newConcrete = dxCreateTexture( "58.png" )
        grassBurn = dxCreateTexture( "70.png" )
        grassMiddleBurn = dxCreateTexture( "27.png" )
        countryRoad = dxCreateTexture( "32.png" )
        sandGrass = dxCreateTexture( "72.png" )
        rockGreen = dxCreateTexture( "75.png" )
        block = dxCreateTexture( "36.png" )
        concGrass = dxCreateTexture( "26.png" )
        parking = dxCreateTexture( "79.png" )
        water = dxCreateTexture( "73.png" )
        brick = dxCreateTexture( "78.png" )
        grassNew = dxCreateTexture( "34.png" )
        grassNew2 = dxCreateTexture( "10.png" )
        
        countryRoad_r = dxCreateTexture( "48.png" )
        leaves = dxCreateTexture( "42.png" )
        leaves2 = dxCreateTexture( "39.png" )
        stalk = dxCreateTexture( "40.png" )
        road_r2 = dxCreateTexture( "5_r2.png" )
        road_rr = dxCreateTexture( "5_rr.png" )
        field = dxCreateTexture( "46.png" )
        cloud = dxCreateTexture( "35.png" )
        if myShader and myImage then
            dxSetShaderValue( myShader, "tex0", myImage )
            dxSetShaderValue( grassShader, "tex0", grassRock )
            dxSetShaderValue( grassShader_r, "tex0", grassRock_r )
            dxSetShaderValue( grassShader_r2, "tex0", grassRock_r2 )
            dxSetShaderValue( grassRoadShader, "tex0", grassRoad )
            dxSetShaderValue( grassRoadShader_r, "tex0", grassRoad_r )
            dxSetShaderValue( rockShader, "tex0", rock )
            dxSetShaderValue( roadShader, "tex0", road )
            dxSetShaderValue( roadShader_r, "tex0", road_r )
            dxSetShaderValue( cocnreteShader_r, "tex0", cocnrete_r )
            dxSetShaderValue( cocnreteShader, "tex0", cocnrete )
            dxSetShaderValue( stoneShader, "tex0", stone )
            dxSetShaderValue( gravelShader, "tex0", gravel )
            dxSetShaderValue( gravelRoadShader, "tex0", gravelRoad )
            dxSetShaderValue( trainShader, "tex0", train )
            dxSetShaderValue( trainGravelShader, "tex0", trainGravel )
            dxSetShaderValue( newConcreteShader, "tex0", newConcrete )
            dxSetShaderValue( grassBurnShader, "tex0", grassBurn )
            dxSetShaderValue( grassMiddleBurnShader, "tex0", grassMiddleBurn )
            dxSetShaderValue( countryRoadShader, "tex0", countryRoad )
            dxSetShaderValue( sandGrassShader, "tex0", sandGrass )
            dxSetShaderValue( rockGreenShader, "tex0", rockGreen )
            dxSetShaderValue( blockShader, "tex0", block )
            dxSetShaderValue( concGrassShader, "tex0", concGrass )
            dxSetShaderValue( parkingShader, "tex0", parking )
            dxSetShaderValue( waterShader, "tex0", water )
            dxSetShaderValue( brickShader, "tex0", brick )
            dxSetShaderValue( grassNewShader, "tex0", grassNew )
            dxSetShaderValue( grassNewShader2, "tex0", grassNew2 )
            dxSetShaderValue( countryRoadShader_r, "tex0", countryRoad_r )
            dxSetShaderValue( leavesShader, "tex0", leaves )
            dxSetShaderValue( leavesShader2, "tex0", leaves2 )
            dxSetShaderValue( stalkShader, "tex0", stalk )
            dxSetShaderValue( roadShader_r2, "tex0", road_r2 )
            dxSetShaderValue( roadShader_rr, "tex0", road_rr )
            dxSetShaderValue( fieldShader, "tex0", field )
            dxSetShaderValue( cloudShader, "tex0", cloud )
            --dxSetShaderValue( grassShader, "tex0", grass )
		--	engineApplyShaderToWorldTexture( myShader, "dt_road*" )
			engineApplyShaderToWorldTexture( fieldShader, "newcrop*" )
			engineApplyShaderToWorldTexture( brickShader, "pisswa" )
			engineApplyShaderToWorldTexture( grassNewShader, "kb_ivy2_256" )
			engineApplyShaderToWorldTexture( grassNewShader, "sm_des_bush2" )
			engineApplyShaderToWorldTexture( grassNewShader2, "sm_des_bush3" )
			engineApplyShaderToWorldTexture( brickShader, "highshopwall1256" )
			engineApplyShaderToWorldTexture( brickShader, "concretemanky" )
			engineApplyShaderToWorldTexture( brickShader, "heliconcrete" )
			engineApplyShaderToWorldTexture( waterShader, "waterclear256" )
			engineApplyShaderToWorldTexture( stoneShader, "sw_stones" )
			engineApplyShaderToWorldTexture( parkingShader, "parking*" )
			engineApplyShaderToWorldTexture( parkingShader, "newgrnd1_128*" )
			engineApplyShaderToWorldTexture( myShader, "des_dustconc" )
			engineApplyShaderToWorldTexture( myShader, "desertgryard256" )
			engineApplyShaderToWorldTexture( myShader, "des_ripplsand" )
			engineApplyShaderToWorldTexture( myShader, "venturas_fwend" )
			engineApplyShaderToWorldTexture( myShader, "desgreengrassmix" )
			engineApplyShaderToWorldTexture( myShader, "desgrassbrn*" )
			engineApplyShaderToWorldTexture( myShader, "sandgrnd128*" )
			engineApplyShaderToWorldTexture( myShader, "yardgrass*" )
			engineApplyShaderToWorldTexture( myShader, "grass*" )
			engineApplyShaderToWorldTexture( myShader, "des_dirt*" )
			engineApplyShaderToWorldTexture( myShader, "des_grass2scrub*" )
			engineApplyShaderToWorldTexture( myShader, "sw_grass01a" )
			engineApplyShaderToWorldTexture( myShader, "sw_grass01" )
			engineApplyShaderToWorldTexture( myShader, "concretedust*" )
			engineApplyShaderToWorldTexture( myShader, "des_quarryrdl" )
			engineApplyShaderToWorldTexture( myShader, "forestfloor*" )
			engineApplyShaderToWorldTexture( rockShader, "vgs_rockmid*" )
			engineApplyShaderToWorldTexture( rockShader, "des_rocky*" )
			engineApplyShaderToWorldTexture( rockShader, "rock_country128" )
			engineApplyShaderToWorldTexture( rockShader, "rocktq128*" )
			engineApplyShaderToWorldTexture( roadShader_r, "tar_1line256hv" )
			engineApplyShaderToWorldTexture( roadShader, "cos_hiway*" )
			engineApplyShaderToWorldTexture( roadShader_r, "desert_1linetar" )
			engineApplyShaderToWorldTexture( rockShader, "cw2_mount*" )
			engineApplyShaderToWorldTexture( roadShader_r, "tar_1linefree*" )
			engineApplyShaderToWorldTexture( roadShader_r, "tar_lineslipway*" )
			engineApplyShaderToWorldTexture( roadShader, "roadnew*" )
			engineApplyShaderToWorldTexture( roadShader_r, "tar_venturasjoin" )
			engineApplyShaderToWorldTexture( roadShader, "hiwayend_256" )
			engineApplyShaderToWorldTexture( roadShader, "vegasroad*" )
			engineApplyShaderToWorldTexture( roadShader_r2, "dt_road" )
			engineApplyShaderToWorldTexture( roadShader, "dt_road_stoplinea" )
			engineApplyShaderToWorldTexture( roadShader_r, "sf_junction5" )
			engineApplyShaderToWorldTexture( roadShader_r2, "hiwaymidlle_256" )
			engineApplyShaderToWorldTexture( cocnreteShader, "bow_abattoir_conc*" )
			engineApplyShaderToWorldTexture( roadShader, "vegasdirtyroad*" )
			engineApplyShaderToWorldTexture( roadShader_r2, "sf_road5" )
			engineApplyShaderToWorldTexture( roadShader, "sf_road*" )
			engineApplyShaderToWorldTexture( roadShader, "ws_freeway3" )
			engineApplyShaderToWorldTexture( roadShader_r, "des_1linetar" )
			engineApplyShaderToWorldTexture( roadShader_r, "desert_1line256" )
			engineApplyShaderToWorldTexture( roadShader_r, "motocross_256" )
			engineApplyShaderToWorldTexture( cocnreteShader_r, "ws_freeway2" )
			engineApplyShaderToWorldTexture( concGrassShader, "sf_pave*" )
			engineApplyShaderToWorldTexture( concGrassShader, "pavebsand256" )
			engineApplyShaderToWorldTexture( concGrassShader, "pavebsandend" )
			engineApplyShaderToWorldTexture( cocnreteShader, "ws_tunnelwall*" )
			engineApplyShaderToWorldTexture( cocnreteShader, "ws_sub_pen_conc" )
			engineApplyShaderToWorldTexture( concGrassShader, "kbpavement*" )
			engineApplyShaderToWorldTexture( roadShader_r, "crossing_law*" )
			engineApplyShaderToWorldTexture( cocnreteShader_r, "stormdrain3*" )
			engineApplyShaderToWorldTexture( cocnreteShader, "stormdrain5*" )
			engineApplyShaderToWorldTexture( cocnreteShader, "block*" )
			--engineApplyShaderToWorldTexture( newConcreteShader, "block2*" )
			engineApplyShaderToWorldTexture( concGrassShader, "newpavement" )
			engineApplyShaderToWorldTexture( myShader, "dirtblendlit" )
			--engineApplyShaderToWorldTexture( grassShader, "desertgravelgrass256" )
			engineApplyShaderToWorldTexture( myShader, "desertgravelgrass256" )
			engineApplyShaderToWorldTexture( myShader, "desertstones256" )
			engineApplyShaderToWorldTexture( grassRoadShader_r, "desertgravelgrassroad" )
			engineApplyShaderToWorldTexture( grassShader, "sw_stonesgrass" )
			engineApplyShaderToWorldTexture( rockGreenShader, "desclifftypebsmix" )
			engineApplyShaderToWorldTexture( rockShader, "sw_rockgrass*" )
			engineApplyShaderToWorldTexture( cocnreteShader_r, "trail_wall1" )
			engineApplyShaderToWorldTexture( cocnreteShader_r, "drvin_ground*" )
			engineApplyShaderToWorldTexture( concGrassShader, "blendpavement*" )
			engineApplyShaderToWorldTexture( concGrassShader, "vegaspavement*" )
			engineApplyShaderToWorldTexture( concGrassShader, "vegasdirtypave*" )
			engineApplyShaderToWorldTexture( cocnreteShader_r, "concreteblock*" )
			engineApplyShaderToWorldTexture( cocnreteShader_r, "vgs_shopwall01_*" )
			engineApplyShaderToWorldTexture( cocnreteShader_r, "dirtywall_256*" )
			engineApplyShaderToWorldTexture( stoneShader, "hiwayoutside_256" )
			engineApplyShaderToWorldTexture( stoneShader, "des_redrock*" )
			engineApplyShaderToWorldTexture( stoneShader, "des_yelrock*" )
			engineApplyShaderToWorldTexture( stoneShader, "sm_rock2_desert*" )
			engineApplyShaderToWorldTexture( trainShader, "ws_traintrax*" )
			engineApplyShaderToWorldTexture( trainGravelShader, "ws_traingravel" )
			engineApplyShaderToWorldTexture( trainGravelShader, "sw_traingravel*" )
			--engineApplyShaderToWorldTexture( roadShader, "tar_freew*" )
			engineApplyShaderToWorldTexture( roadShader_r, "tar_1line256hvblenddrt" )
			engineApplyShaderToWorldTexture( roadShader_rr, "tar_freewyleft" )
			engineApplyShaderToWorldTexture( roadShader_rr, "tar_freewyright" )
			--engineApplyShaderToWorldTexture( roadShader_r, "tar_freew*" )
			engineApplyShaderToWorldTexture( roadShader_r2, "snpedtest1" )
			engineApplyShaderToWorldTexture( grassShader_r, "sfn_rocktbrn128" )
			engineApplyShaderToWorldTexture( grassShader, "sfncn_rockgrass3" )
			engineApplyShaderToWorldTexture( grassShader_r, "rocktbrn128blnd" )
			engineApplyShaderToWorldTexture( grassShader, "rocktq128_grass4blend" )
			engineApplyShaderToWorldTexture( grassShader_r2, "vgs_rockbot*" )
			engineApplyShaderToWorldTexture( grassShader_r, "rock_country128blnd" )
			engineApplyShaderToWorldTexture( myShader, "desgreengrass" )
			engineApplyShaderToWorldTexture( myShader, "hiwaygravel*" )
			engineApplyShaderToWorldTexture( myShader, "hiway2sand*" )
			engineApplyShaderToWorldTexture( myShader, "des_scrub*" )
			engineApplyShaderToWorldTexture( myShader, "bow_church_grass_gen" )
			engineApplyShaderToWorldTexture( grassMiddleBurnShader, "sfn_rockhole" )
			engineApplyShaderToWorldTexture( grassRoadShader, "dt_road2grasstype4" )
			engineApplyShaderToWorldTexture( grassRoadShader, "hiwayinsideblend*" )
			--engineApplyShaderToWorldTexture( grassRoadShader, "hiwayinside5*" )
			--engineApplyShaderToWorldTexture( grassRoadShader, "hiwayinside*" )
			engineApplyShaderToWorldTexture( myShader, "hiwayinside*" )
			--engineApplyShaderToWorldTexture( myShader, "hiwayinside5*" )
			--engineApplyShaderToWorldTexture( grassRoadShader, "cuntroad01_law" )
			engineApplyShaderToWorldTexture( roadShader_r2, "cuntroad01_law" )
			engineApplyShaderToWorldTexture( roadShader_r, "des_1line256" )
			engineApplyShaderToWorldTexture( roadShader_r, "des_1lineend" )
			engineApplyShaderToWorldTexture( roadShader_rr, "greycrossing" )
			engineApplyShaderToWorldTexture( grassRoadShader_r, "brngrss2stones" )
			engineApplyShaderToWorldTexture( grassRoadShader_r, "des_roadedge*" )
			engineApplyShaderToWorldTexture( myShader, "des_grass2dirt*" )
			engineApplyShaderToWorldTexture( myShader, "des_grass2dirt*" )
			engineApplyShaderToWorldTexture( myShader, "desstones_dirt*" )
			--engineApplyShaderToWorldTexture( grassShader, "txgrass0_1" )
			engineApplyShaderToWorldTexture( gravelShader, "bow_grass_gryard" )
			--engineApplyShaderToWorldTexture( gravelShader, "desertstones256" )
			engineApplyShaderToWorldTexture( countryRoadShader, "desmudtrail" )
			engineApplyShaderToWorldTexture( countryRoadShader, "dirttrack*" )
			engineApplyShaderToWorldTexture( countryRoadShader_r, "tar_1line256hvtodirt" )
			engineApplyShaderToWorldTexture( countryRoadShader, "cw2_weeroad*" )
			
			engineApplyShaderToWorldTexture( blockShader, "ws_airpt_concrete" )
			engineApplyShaderToWorldTexture( blockShader, "plaintarmac1" )
			engineApplyShaderToWorldTexture( blockShader, "ws_carparknew2" )
			engineApplyShaderToWorldTexture( blockShader, "greyground256" )
			
			engineApplyShaderToWorldTexture( sandGrassShader, "sw_sandgrass" )
			engineApplyShaderToWorldTexture( cloudShader, "cloud1" )
			engineApplyShaderToWorldTexture( cloudShader, "cloudmasked" )
			
			
			-- деревья
			engineApplyShaderToWorldTexture( leavesShader2, "sm_josh_leaf*" )
			engineApplyShaderToWorldTexture( stalkShader, "sm_josh_bark*" )
			
			
			engineApplyShaderToWorldTexture( leavesShader, "newtreeleaves*" )
			engineApplyShaderToWorldTexture( leavesShader, "pinelo*" )
			engineApplyShaderToWorldTexture( leavesShader, "planta*" )
			engineApplyShaderToWorldTexture( leavesShader, "newtreed256*" )
			engineApplyShaderToWorldTexture( leavesShader, "kb_ivy*" )
			engineApplyShaderToWorldTexture( leavesShader, "sm_pinetreebit*" )
			engineApplyShaderToWorldTexture( leavesShader, "tree*" )
			engineApplyShaderToWorldTexture( leavesShader, "cypress*" )
			engineApplyShaderToWorldTexture( leavesShader, "kbtree4*" )
			engineApplyShaderToWorldTexture( leavesShader, "trunk3*" )
			engineApplyShaderToWorldTexture( leavesShader, "elm_treegrn*" )
			engineApplyShaderToWorldTexture( leavesShader, "cedar*" )
			engineApplyShaderToWorldTexture( leavesShader, "coral" )
			engineApplyShaderToWorldTexture( leavesShader, "oakleaf*" )
			engineApplyShaderToWorldTexture( leavesShader, "pinebranch*" )
			
			
		--	engineApplyShaderToWorldTexture( myShader, "bullethitsmoke*" )
	--		engineApplyShaderToWorldTexture( myShader, "monsterb92wheel64", myImage )
            outputChatBox( "Shader using techinque " .. tecName ) --txgrass0_1
        else
            outputChatBox( "Problem - use: debugscript 3" )
        end
    end
)

